[project]
authors = ["Quentin Febvre <quentin.febvre@imt-atlantique.fr>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "zendag"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"

[pypi-dependencies]
zendag = {path= ".", extras=["dev"], editable=true}

